### ISSUE TITLE
View Helper 參數格式不對

### ISSUE THREAD

**Issue by glasses618** [ZneuRay/spgateway_rails#1]
README 說明是這樣用
```ruby
spgateway_periodical_form(
        btn_value: "付款",
        btn_class: "btn btn-primary")
```
但是 method 的參數不是用 keyword arguments 收的，因此會噴錯 (no implicit conversion of Hash into String)
https://github.com/ZneuRay/spgateway_rails/blob/40e0f1d95bc0b9e1d6677c97eb2296a93b6c5c74/lib/spgateway_rails/view_helper.rb#L8

https://github.com/ZneuRay/spgateway_rails/blob/40e0f1d95bc0b9e1d6677c97eb2296a93b6c5c74/lib/spgateway_rails/view_helper.rb#L24

**Comment by ZneuRay** [comment]
好的，太感謝你了，我稍後修正
